### PR TITLE
PM1 - SOAP service - second PR

### PR DESCRIPTION
**Pull request by Mchapuis**
We should remove the previous pull request. Some errors were made in the previous branch. 

Based on the original pull request, here are the changes:
a) and b) I have purged the content of bin/ since it was not necessary.
c) all the lib are located in scr/lib with the correct path
d) Marie corrected the error with java.io.File
e) I added a simple README_webServices.txt file to locate the files we created. To be updated later for REST.

### CODE REVIEW

**Comment by smokhov** [comment]
@jashanj0tsingh -- please review and merge. I have changed the destination branch to our `Datasets` since this where it belongs until `temp`, `Datasets`, etc are all merged into master.

**Comment by smokhov** [comment]
(This is a successor of PR #5)

**Comment by Mchapuis** [comment]
We still need to push some files to complete the PM1 part 3. This should be completed this week.

**Comment by smokhov** [comment]
@Mchapuis -- assuming PM1.3 is complete more or less here so you can move on to complete and submit PR2.3 ASAP

@jashanj0tsingh -- please review and merge into `Datasets` ASAP, with anything required to mod so the team can rebase their fork to continue their work; at the same time you can evaluate PM1.3

**Comment by Mchapuis** [comment]
We still need to complete the client for PM1.3 since the person responsible for it had a lot of trouble with the project and openESB. Someone else is doing it right now.

PM2.3 is nearly done, @jdesorm1 is fixing the issue we had last week.

**Review by jashanj0tsingh — CHANGES_REQUESTED** [review]
1. Documentation/ README needs to be more succinct. 
2. A simple yet self-explanatory client is required to demonstrate the capabilities of the service in itself. 
3. Weed out `getxxxx()` methods from the potential client for example getOverrideFiles should come into action once the response has been received as a string and then the client should be responsible to check whether existing files need to be overwritten or not. (which as you have mentioned is still yet expected)
4. `setDefault()` should work in order to get a response based on hard coded values unless overridden by relative `setxx()` method. 
5. Minor, but advisable to put the required jars at a relative path with the project structure instead of still manually adding `jdom` and `dom4j` explicitly.
6. Cannot seem to test the web service locally as well so a demo is required for sure.
7. More changes will be required once a working client is demoed.

**Comment by jashanj0tsingh** [comment]
@Mchapuis I am still unable to find a README. Can you point me to it?

**Comment by Mchapuis** [comment]
Good news, we are done with PM1 part3 !!!

1- updated the README for soap service
2-Client is working. 
3-We got rid of al the get...() web methods
4-SetDefault is working
5-Not sure how to setup a relative path for the two jars that are always disconnected.
6-We can demo it wednesday if you want. It would be easier for you.

**Comment by smokhov** [comment]
@jashanj0tsingh -- locally, please create a branch off the tip of `Datasets`, called `WS`; then change the base of this PR to the `WS` branch. When ready to merge, merge. Then move on to PR #8 to do the same.

**Review by jashanj0tsingh — APPROVED** [review]

**Comment by jashanj0tsingh** [comment]
Requires more work on the README guys. So far I was able to test the client but failed to do the same within the browser using OpenESB `Test Web Service`. The SOAP response either return weird strings or `java heap error`. @smokhov Is it significant (to be able to test the Web Service via OpenESB browser tests) in terms of ensuring proper working? The merge is on hold for now but graded with comments.

**Comment by Mchapuis** [comment]
@jashanj0tsingh We did a java client console for the client. I hope it's ok, since it was not specified what kind of client we had to do.

Both me and @jdesorm1 could run the `Test Web Service` correctly with the SOAP service. We can demonstrate it during the lab this week.

**Comment by smokhov** [comment]
@jashanj0tsingh -- OK to merge. @Mchapuis 's team will demo as promised.

**Pull request merged**
