### PR TITLE
PM2 - REST services 

### PR DESCRIPTION
**Pull request by Mchapuis**
This is the PM2 part 3 without the soap service. 

To run the client for the rest service, go to Web Pages/RestJSClient.html

### CODE REVIEW

**Comment by smokhov** [comment]
@jashanj0tsingh -- after PR #7 is merged, proceed with this one. After you change its base to `WS`, this PR will have fewer commits skipping the ones that will have been merged by then in PR #7. Then can review the remaining commits to avoid clutter.

**Comment by smokhov** [comment]
@Mchapuis -- you should not have made this PR from your `Datasets`, it should have come out from your `PM2` branch to avoid mixing.

**Comment by smokhov** [comment]
@Mchapuis but leave it as is for now; don't undo or redo anything at this time

**Comment by Mchapuis** [comment]
@smokhov I updated the `Datasets` branch and merged the `PM2` into it...but I realize now that this is confusing because I got the changes from the soap service as well. 

I will wait before changing anything

**Comment by jashanj0tsingh** [comment]
This project is not deployable, @smokhov @Mchapuis I have not gone into commits history in detail but since SOAP web service for the same is missing when I try to test it locally, will the merge from PR#7 fix it? Not so sure about it.

**Comment by Mchapuis** [comment]
@jashanj0tsingh I think not all SOAP service is in here, I looked at the Main.java file and it's not the same. I can cancel this pull request and redo it with the right branch for REST service.

Maybe that's why there are problems. I had a lot of merge conflict and so this is probably why it can't deploy. I didn't test the branch to see if it was deployable after the merge

**Comment by smokhov** [comment]
@Mchapuis don't "cancel" this PR; @jashanj0tsingh should have merged PR #7 before doing any work on this PR; however don't do anything until the PR #7 merge has happened.

**Comment by jashanj0tsingh** [comment]
@Mchapuis As per @smokhov the merge is done. Now you can make a few changes you wanted in order to make it deployable and other changes you wanted to do so.

**Comment by smokhov** [comment]
Need to fix conflicts for `README_webServices.txt`; I've reset the base to `WS`, so we see fewer commits in the pipeline, and so it is easier to reviews. @Mchapuis @jashanj0tsingh

**Comment by Mchapuis** [comment]
Should I remove all SOAP service from this pull request or fix it so that the SOAP and REST services work here?

**Comment by smokhov** [comment]
@Mchapuis NO.

**Comment by smokhov** [comment]
@Mchapuis do now any directly related fixes here on your `Datasets` branch. Including making sure your `Main`, etc. whatever is same for deployment. This PR is now mostly clear from PM1 stuff in its commit history, so you can easily see the diffs.

**Comment by Mchapuis** [comment]
@smokhov The commit `Merge branch 'branch_to_be_merged_Dataset' into Datasets   ---  f61cfaa` is the SOAP service. 

I can clear this out with you tomorrow.

**Pull request merged**
